# Résolution polaire d'un système

In [52]:
import numpy as np
from math import sqrt, exp

In [144]:
def Gram_Schmidt(U, ps) :
    A=U.copy()
    d = len(A)
    B = np.zeros((d,d))
    for i in range(d):
        for j in range(i):
            B[i][j] = ps(A[i],A[j])
            A[i] = A[i]-ps(A[i],A[j])*A[j]
        if ps(A[i],A[i]) == 0 :
            print("La famille est liée")
            return None
        else :
            B[i][i] = sqrt(ps(A[i],A[i]))
            A[i]=1/sqrt(ps(A[i],A[i]))*A[i]
    return A, B
   

In [145]:
U = np.array([[2,0,1],[0,0,2],[1,2,1]], dtype=float)

In [146]:
def produit_scalaire(x,y):
    n = len(x)
    p = 0
    for i in range(n) :
        p = p + x[i]*y[i]
    return p
        

In [147]:
A,B=Gram_Schmidt(U, produit_scalaire)
A,B

(array([[ 8.94427191e-01,  0.00000000e+00,  4.47213595e-01],
        [-4.47213595e-01,  0.00000000e+00,  8.94427191e-01],
        [ 2.77555756e-17,  1.00000000e+00, -2.77555756e-17]]),
 array([[2.23606798, 0.        , 0.        ],
        [0.89442719, 1.78885438, 0.        ],
        [1.34164079, 0.4472136 , 2.        ]]))

In [148]:
np.dot(B,A)

array([[2., 0., 1.],
       [0., 0., 2.],
       [1., 2., 1.]])

In [149]:
np.dot(A,A.T)

array([[ 1.00000000e+00,  6.22456065e-17,  1.24126708e-17],
       [ 6.22456065e-17,  1.00000000e+00, -3.72380123e-17],
       [ 1.24126708e-17, -3.72380123e-17,  1.00000000e+00]])

In [150]:
def solve_under(A,b):
    n = len(A)
    x=np.zeros(n)
    for i in range(n):
        x[i]=b[i]
        for j in range(i):
            x[i]=x[i]-x[j]*A[i][j]
        x[i]=x[i]/A[i][i]
    return x

In [151]:
solve_under(B,[1,2,3])

array([0.4472136 , 0.89442719, 1.        ])

In [152]:
np.dot(B,[0.4472136 , 0.89442719, 1.        ])

array([1.00000001, 2.        , 3.00000001])

In [153]:
def solve_gram_schmidt(C,b):
    G, L = Gram_Schmidt(C,produit_scalaire)
    y = solve_under(L,b)
    x = np.dot(G.T,y)
    return x
    

In [154]:
solve_gram_schmidt(U,[1,2,3])

array([-3.44900309e-17,  1.00000000e+00,  1.00000000e+00])

In [155]:
np.dot(U,[-3.44900309e-17,  1.00000000e+00,  1.00000000e+00])

array([1., 2., 3.])

# Interpolation de Lagrange

In [183]:
n = 10
xis=np.array([i/n for i in range(n+1)])
A = np.array([xis**i for i in range(n+1)]).T
#A

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.00000000e-01, 1.00000000e-02, 1.00000000e-03,
        1.00000000e-04, 1.00000000e-05, 1.00000000e-06, 1.00000000e-07,
        1.00000000e-08, 1.00000000e-09, 1.00000000e-10],
       [1.00000000e+00, 2.00000000e-01, 4.00000000e-02, 8.00000000e-03,
        1.60000000e-03, 3.20000000e-04, 6.40000000e-05, 1.28000000e-05,
        2.56000000e-06, 5.12000000e-07, 1.02400000e-07],
       [1.00000000e+00, 3.00000000e-01, 9.00000000e-02, 2.70000000e-02,
        8.10000000e-03, 2.43000000e-03, 7.29000000e-04, 2.18700000e-04,
        6.56100000e-05, 1.96830000e-05, 5.90490000e-06],
       [1.00000000e+00, 4.00000000e-01, 1.60000000e-01, 6.40000000e-02,
        2.56000000e-02, 1.02400000e-02, 4.09600000e-03, 1.63840000e-03,
        6.55360000e-04, 2.62144000e-04, 1.04857600e-

In [180]:
b=[exp(i/n) for i in range(n+1) ]

In [182]:
coeff=solve_gram_schmidt(A,b)
coeff

array([1.00000000e+00, 1.00000000e+00, 5.00000000e-01, 1.66666662e-01,
       4.16666993e-02, 8.33320133e-03, 1.38923428e-03, 1.97816834e-04,
       2.54721318e-05, 2.28651214e-06, 4.55935665e-07])

In [184]:
np.dot(A,coeff)

array([1.        , 1.10517092, 1.22140276, 1.34985881, 1.4918247 ,
       1.64872127, 1.8221188 , 2.01375271, 2.22554093, 2.45960311,
       2.71828183])

In [186]:
integrale=0
for i in range(n+1):
    integrale=integrale+coeff[i]/(i+1)
integrale

1.718281828459044

# Méthodes d'intégration

In [188]:
def integrale_rectangle(f,n):
    integrale=0
    for i in range(n):
        integrale=integrale+1/n*f(i/n)
    return integrale

In [196]:
integrale_rectangle(exp,20)

1.6756827432137449

In [197]:
def integrale_trapeze(f,n):
    integrale=0
    for i in range(n):
        integrale=integrale+1/(2*n)*(f(i/n)+f((i+1)/n))
    return integrale

In [198]:
integrale_trapeze(exp,20)

1.7186397889252212

In [199]:
exp(1)-1

1.718281828459045

In [201]:
def integrale_simpson(f,n):
    integrale = 0
    for i in range(n):
        integrale=integrale+1/(n*6)*(f(i/n)+f((i+1)/n)+4*f((i+1/2)/n))
    return integrale
    

In [202]:
integrale_simpson(exp, n)

1.7182818881038568