# Pivot de Gauss

In [2]:
import numpy as np
from math import sqrt

In [3]:
def echangeLigne(A,i,j) :
    if i == j:
        return A
    else :
        x = A[i].copy()
        A[i] = A[j]
        A[j] = x
        return A

In [4]:
def Cherche_non_nul(A,i):
    n = len(A[0])
    for j in range(i,n) :
        if A[j][i] != 0 :
            return (True,j)
            break
    return (False,0)
        

In [5]:
b = np.array([[2,0,1],[0,0,2],[1,2,1]], dtype=float)
print(Cherche_non_nul(b,1))

(True, 2)


In [6]:
def pivot_gauss(A):
    n = len(A[0])
    for i in range(n-1):
        if Cherche_non_nul(A,i)[0] :
            echangeLigne(A,i, Cherche_non_nul(A,i)[1])
            for j in range(i+1,n):
                A[j] = A[j] - A[j][i]/A[i][i]*A[i]
        else:
            return 0, A
            break
    det = 1
    for i in range(n) :
        det = det*A[i][i]
    return det, A
        
            

In [7]:
pivot_gauss(b)

(8.0, array([[2. , 0. , 1. ],
        [0. , 2. , 0.5],
        [0. , 0. , 2. ]]))

In [8]:
A=np.zeros((58,58), dtype=float)
for i in range(58) :
    for j in range(58) :
        A[i,j]= abs(i-j)+1
pivot_gauss(A)

(-4.25139804823397e+18,
 array([[ 1.00000000e+00,  2.00000000e+00,  3.00000000e+00, ...,
          5.60000000e+01,  5.70000000e+01,  5.80000000e+01],
        [ 0.00000000e+00, -3.00000000e+00, -4.00000000e+00, ...,
         -5.70000000e+01, -5.80000000e+01, -5.90000000e+01],
        [ 0.00000000e+00,  0.00000000e+00, -2.66666667e+00, ...,
         -3.80000000e+01, -3.86666667e+01, -3.93333333e+01],
        ...,
        [ 0.00000000e+00,  0.00000000e+00, -1.54757605e-27, ...,
         -2.03571429e+00, -2.07142857e+00, -2.10714286e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.78780793e-28, ...,
          0.00000000e+00, -2.03508772e+00, -2.07017544e+00],
        [ 0.00000000e+00,  0.00000000e+00,  2.05870935e-27, ...,
          0.00000000e+00,  0.00000000e+00, -2.03448276e+00]]))

# Orthonormalisation de Gram - Schmidt

In [9]:
def Gram_Schmidt(A, ps) :
    d = len(A)
    for i in range(d):
        for j in range(i):
            A[i] = A[i]-ps(A[i],A[j])*A[j]
        if ps(A[i],A[i]) == 0 :
            print("La famille est liée")
            return None
        else :
            A[i]=1/sqrt(ps(A[i],A[i]))*A[i]
    return A
        
        

In [10]:
def produit_scalaire(x,y):
    n = len(x)
    p = 0
    for i in range(n) :
        p = p + x[i]*y[i]
    return p
        

In [11]:
Gram_Schmidt(b,produit_scalaire)

array([[ 0.89442719,  0.        ,  0.4472136 ],
       [-0.09759001,  0.97590007,  0.19518001],
       [-0.43643578, -0.21821789,  0.87287156]])

In [12]:
produit_scalaire([ 0.26726124,  0.80178373, -0.53452248],[ 0.26726124,  0.80178373, -0.53452248])

1.0000000017244008

In [13]:
def produit_scalaire_polynome(x,y):
    n = len(x)
    p = 0
    for i in range(2*n-1):
        for j in range (max(0,i-n+1),min(i+1, n)):
            p = p + x[j]*y[i-j]/(i+1)
    return p
        

In [14]:
produit_scalaire_polynome

<function __main__.produit_scalaire_polynome(x, y)>

In [15]:
A = np.identity(10, dtype=float)
Gram_Schmidt(A,produit_scalaire_polynome)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.73205081e+00,  3.46410162e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 2.23606798e+00, -1.34164079e+01,  1.34164079e+01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-2.64575131e+00,  3.17490157e+01, -7.93725393e+01,
         5.29150262e+01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 3.00000000e+00, -6.00000000e+01,  2.70000000e+02,
        -4.20000000e+02,  2.10000000e+02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.

In [97]:
produit_scalaire_polynome([-4.35867260e+00,  3.92284452e+02, -8.63033351e+03,
         8.05503767e+04, -3.92685530e+05,  1.09952523e+06,
        -1.83255013e+06,  1.79515788e+06, -9.53680681e+05,
         2.11929627e+05],[-4.35867260e+00,  3.92284452e+02, -8.63033351e+03,
         8.05503767e+04, -3.92685530e+05,  1.09952523e+06,
        -1.83255013e+06,  1.79515788e+06, -9.53680681e+05,
         2.11929627e+05])

0.999964714050293